#!#/bin/bash  MAKE INTO A .sh file eventually

#Helpful Guides:
#https://github.com/ansible/awx/blob/devel/INSTALL.md
#https://github.com/ansible/awx-operator (perfered way to install AWX)



#Required: Kubernetes, AWX, AWX CLI



#Kubernetes Install
curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
#https://kubectl.docs.kubernetes.io/installation/kustomize/binaries/



#AWX Install
touch kustomization.yaml

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Find the latest tag here: https://github.com/ansible/awx-operator/releases
  - github.com/ansible/awx-operator/config/default?ref=<tag>

# Set the image tags to match the git version from above
images:
  - name: quay.io/ansible/awx-operator
    newTag: <tag>

# Specify a custom namespace in which to install AWX
namespace: awx
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

kubectl get pods -n awx




#Make sure to add this new file to the list of "resources" in your 'kustomization.yaml' file:

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
resources:
  - github.com/ansible/awx-operator/config/default?ref=<tag>
  # Add this extra line:
  - awx-demo.yaml
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

#Finally, run kustomize again to create the AWX instance in your cluster:
kustomize build . | kubectl apply -f -

#After a few minutes, the new AWX instance will be deployed. You can look at the operator pod logs in order to know where the installation process is at:
kubectl logs -f deployments/awx-operator-controller-manager -c awx-manager


#Once deployed, the AWX instance will be accessible by running:
minikube service -n awx awx-demo-service --url


#By default, the admin user is 'admin' and the password is available in the <resourcename>-admin-password secret. To retrieve the admin password, run:
kubectl get secret awx-demo-admin-password -o jsonpath="{.data.password}" | base64 --decode ; echo
#yDL2Cx5Za94g9MvBP6B73nzVLlmfgPjR


#AWX CLI
pip3 install awxkit
awx --help
