version: '3'
services:
    jellyseerr:
       image: fallenbagel/jellyseerr:latest
       container_name: jellyseerr
       environment:
            - LOG_LEVEL=debug
            - TZ=Asia/Tashkent
       ports:
            - 5055:5055
       volumes:
            - /path/to/appdata/config:/app/config
       restart: unless-stopped
 #https://hub.docker.com/r/fallenbagel/jellyseerr
    radarr:
       image: lscr.io/linuxserver/radarr:latest
       container_name: radarr
       environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
       volumes:
             - /path/to/data:/config
             - /path/to/movies:/movies #optional
             - /path/to/downloadclient-downloads:/downloads #optional
       ports:
             - 7878:7878
       restart: unless-stopped
#https://hub.docker.com/r/linuxserver/radarr

    sonarr:
       image: lscr.io/linuxserver/sonarr:latest
       container_name: sonarr
       environment:
             - PUID=1000
             - PGID=1000
             - TZ=Europe/London
       volumes:
             - /path/to/data:/config
             - /path/to/tvseries:/tv #optional
             - /path/to/downloadclient-downloads:/downloads #optional
       ports:
             - 8989:8989
       restart: unless-stopped
#https://hub.docker.com/r/linuxserver/sonarr
       
    prowlarr:
       image: lscr.io/linuxserver/prowlarr:develop
       container_name: prowlarr
       environment:
             - PUID=1000
             - PGID=1000
             - TZ=Europe/London
       volumes:
             - /path/to/data:/config
       ports:
             - 9696:9696
       restart: unless-stopped
#https://hub.docker.com/r/linuxserver/prowlarr


