#!/bin/bash

echo "################################################################"
echo "#################### Debian Install Scrip ######################"
echo "################################################################"



echo "####################    Updating    #######################"
sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get dist-upgrade -y
sudo apt-get autoremove -y
echo "####################    Updated    #######################"



echo "####################    Installing Software   #######################"

echo "####################    Software Installed    #######################"



echo "####################    After Software Updates    #######################"
sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get dist-upgrade -y
sudo apt-get autoremove -y
echo "####################    Completed    #######################"



echo "######################################################"
echo "#################### Completed #######################"
echo "######################################################"
